# Project identification
sonar.projectKey=YamiDarknezz_inventory-api
sonar.organization=<USER>darknezz

# Project metadata
sonar.projectName=inventory-api
sonar.projectVersion=0.1.0

# Source code
sonar.sources=src/main/java
sonar.sourceEncoding=UTF-8

# Tests
sonar.tests=src/test/java

# Java + JaCoCo coverage
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

# Exclusions
sonar.exclusions=\
  **/dto/**,\
  **/config/DataSeeder.java,\
  **/config/OpenApiConfig.java,\
  **/InventoryApiApplication.java